apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - port: 4173        # Service port (inside cluster)
      targetPort: 4173  # Container port
      nodePort: 30036   # or remove to auto-assign
